// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkeDxLtnJvMfheFJ_UbMIFGYHUPUTBdxY',
    appId: '1:1072520543866:web:7568d1ddded97b4d4d05c3',
    messagingSenderId: '1072520543866',
    projectId: 'hrbabelrian',
    authDomain: 'hrbabelrian.firebaseapp.com',
    storageBucket: 'hrbabelrian.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzFBGN5bv2s8ky-QJopwMJnbMv0pmnCmg',
    appId: '1:1072520543866:android:8aba8375d19558424d05c3',
    messagingSenderId: '1072520543866',
    projectId: 'hrbabelrian',
    storageBucket: 'hrbabelrian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsgUhx2kMXI8kPqdMErJW07p-v0d0skNo',
    appId: '1:1072520543866:ios:ee5b308c34fd10c34d05c3',
    messagingSenderId: '1072520543866',
    projectId: 'hrbabelrian',
    storageBucket: 'hrbabelrian.appspot.com',
    iosClientId: '1072520543866-bpgc4aq6t4p58jplth1h8eqhe04kfk8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrBabElrian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsgUhx2kMXI8kPqdMErJW07p-v0d0skNo',
    appId: '1:1072520543866:ios:ee5b308c34fd10c34d05c3',
    messagingSenderId: '1072520543866',
    projectId: 'hrbabelrian',
    storageBucket: 'hrbabelrian.appspot.com',
    iosClientId: '1072520543866-bpgc4aq6t4p58jplth1h8eqhe04kfk8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrBabElrian',
  );
}
